version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - ENVIRONMENT=development
    command: uvicorn src.presentation.api:app --host 0.0.0.0 --port 8000 --reload
